### ISSUE TITLE
make html

### ISSUE THREAD

**Issue by CriscelyLP** [osmose-model/user_documentation#1]
Could not import extension sphinxcontrib.bibtex (exception: No module named 'sphinxcontrib.bibtex')
make: *** [Makefile:20: html] Error 1

**Comment by barriern** [comment]
Hi Criscely.

You need to install additional python packages. What kind of Python do you use? Did you install one from Anaconda?

Nicolas

**Comment by CriscelyLP** [comment]
I tried first Python 2 and then Python 3 in my system (Fedora 27).
But after install Python2.7 from ANACONDA (https://www.anaconda.com/download/), and then the libraries (sphinxcontrib.bibtex and additional libraries), everything was solved!

Thank you Nicolas!
